import { ModeToggle } from '@/components/theme/mode-toggle'
import { ThemeProvider } from '@/components/theme/theme-provider'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='font-sans antialiased' suppressHydrationWarning>
      <body className='bg-background text-foreground'>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {/* Header */}
          <header className='border-b border-border'>
            <div className='mx-auto flex max-w-350 items-center justify-between gap-4 px-4.5 py-3'>
              {/* Logo */}
              <div className='font-mono text-xl font-extrabold'>
                WDC<span className='text-primary-text'>T</span>
              </div>

              {/* Theme Toggle */}
              <ModeToggle />
            </div>
          </header>

          {/* Main */}
          <main className='mx-auto min-h-screen max-w-350 border-r border-l border-border px-4.5 py-26'>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
